export const ROLES = {
  FSE: 'FSE',
  TEAM_LEADER: 'TEAM_LEADER',
  WAREHOUSE: 'WAREHOUSE',
  DISPATCH: 'DISPATCH',
  ADMIN: 'ADMIN'
};

export const ORDER_STATUS = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SENT_BACK: 'SENT_BACK',
  STOCK_CONFIRMED: 'STOCK_CONFIRMED',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  DISPATCHED: 'DISPATCHED',
  DELIVERED: 'DELIVERED'
};

export const TEAM_LEADER_TRANSITIONS = {
  SUBMITTED: [ORDER_STATUS.APPROVED, ORDER_STATUS.REJECTED, ORDER_STATUS.SENT_BACK],
  UNDER_REVIEW: [ORDER_STATUS.APPROVED, ORDER_STATUS.REJECTED, ORDER_STATUS.SENT_BACK]
};